### PR TITLE
Add "add" operation to update values, and divide operations for pixel intersections.

### PR DESCRIPTION
**Pull request by erykoff**
These routines should make it easy to use healsparse to (e.g.) compute the pixelized mean of a scalar field.

### CODE REVIEW

**Comment by esheldon** [comment]
I think when `operation='add'` it is not adding to the map but rather setting the value.  Here is an example script and output
```python
import healsparse as hsp
import numpy as np
import esutil as eu


def do_sums(num, denom, ra, dec, vals):
    num.update_values_pos(
        ra,
        dec,
        vals,
        operation='add',
    )
    denom.update_values_pos(
        ra,
        dec,
        np.ones(ra.size),
        operation='add',
    )


rng = np.random.RandomState(123)

npoly = 100000
poly_val = 1.0
circle_val = 2.0

nside_coverage = 32
nside_map = 64

num = hsp.HealSparseMap.make_empty(nside_coverage, nside_map, np.float64)
denom = hsp.HealSparseMap.make_empty(nside_coverage, nside_map, np.float64)

ra_max = 210
ra_min = 200
dec_max = 10.0
dec_min = 0.0

# approximate area
area = (ra_max - ra_min) * (dec_max - dec_min)
density = npoly / area

circ_ra_cen = 0.5 * (ra_max + ra_min)
circ_dec_cen = 0.5 * (dec_max + dec_min)
circle_rad = 3.0
circle_area = np.pi * circle_rad**2
ncircle = int(circle_area * density)


poly_ra, poly_dec = eu.coords.randsphere(
    npoly,
    ra_range=(ra_min, ra_max),
    dec_range=(dec_min, dec_max),
    rng=rng,
)
circle_ra, circle_dec = eu.coords.randcap(
    nrand=ncircle,
    ra=circ_ra_cen,
    dec=circ_dec_cen,
    rad=circle_rad,
    rng=rng,
)
test_circle_ra, test_circle_dec = eu.coords.randcap(
    nrand=10,
    ra=circ_ra_cen,
    dec=circ_dec_cen,
    rad=circle_rad,
    rng=rng,
)

poly_vals = np.zeros(npoly) + poly_val
circle_vals = np.zeros(ncircle) + circle_val

do_sums(num, denom, poly_ra, poly_dec, poly_vals)

avg_map0 = hsp.divide_intersection([num, denom])
test_circ_vals = avg_map0.get_values_pos(test_circle_ra, test_circle_dec)
test_num_vals = num.get_values_pos(test_circle_ra, test_circle_dec)
test_denom_vals = denom.get_values_pos(test_circle_ra, test_circle_dec)
print('after sums for poly')
print('-'*70)
print(test_num_vals)
print(test_denom_vals)
print(test_circ_vals)

do_sums(num, denom, circle_ra, circle_dec, circle_vals)

avg_map = hsp.divide_intersection([num, denom])

test_circ_vals = avg_map.get_values_pos(test_circle_ra, test_circle_dec)
test_num_vals = num.get_values_pos(test_circle_ra, test_circle_dec)
test_denom_vals = denom.get_values_pos(test_circle_ra, test_circle_dec)

print('after sums for circle')
print('-'*70)
print(test_num_vals)
print(test_denom_vals)
print(test_circ_vals)
```
Output
```
after sums for poly
----------------------------------------------------------------------
[842. 839. 815. 837. 850. 879. 871. 837. 812. 802.]
[842. 839. 815. 837. 850. 879. 871. 837. 812. 802.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
after sums for circle
----------------------------------------------------------------------
[1700. 1470. 1670. 1786. 1714. 1700. 1656. 1786. 1106. 1602.]
[850. 735. 835. 893. 857. 850. 828. 893. 553. 801.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]

```

**Comment by esheldon** [comment]
Because the polygon area here encompasses the circle, the average in the circle should be 1.5

**Comment by esheldon** [comment]
I set the sentinel to 0.0 and seems to work.  I thought the docs said that sentinel values would be set to zero before adding, so maybe that's a bug.

**Comment by erykoff** [comment]
Thanks for pointing this out!  There was a bug in the way that values were being reset, and this wasn't actually covered by the tests.  Please try again now!

**Comment by erykoff** [comment]
Also, I ran your test code and it now says for me:

```
after sums for poly
----------------------------------------------------------------------
[842. 839. 815. 837. 850. 879. 871. 837. 812. 802.]
[842. 839. 815. 837. 850. 879. 871. 837. 812. 802.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
after sums for circle
----------------------------------------------------------------------
[2542. 2309. 2485. 2623. 2564. 2579. 2527. 2623. 1918. 2404.]
[1692. 1574. 1650. 1730. 1707. 1729. 1699. 1730. 1365. 1603.]
[1.50236407 1.46696315 1.50606061 1.51618497 1.50205038 1.49161365
 1.4873455  1.51618497 1.40512821 1.49968808]
```

**Comment by esheldon** [comment]
Yes, works now

**Comment by erykoff** [comment]
Great!  Can you formally review?  It's not much.  Thanks!

**Comment by esheldon** [comment]
test

**Review by esheldon — APPROVED** [review]

**Comment by esheldon** [comment]
For that plot I changed to `nside_map = 256`.  Looks good

**Pull request merged**
