### PR TITLE
Add support for boolean-valued maps.

### PR DESCRIPTION
**Pull request by erykoff**
Note that these can only be serialized with parquet and not fits.

### CODE REVIEW

**Comment by erykoff** [comment]
This addresses #122.

**Comment by esheldon** [comment]
why doesn't it work with fits?

**Comment by erykoff** [comment]
Fits doesn’t support Boolean images. https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node40.html (Also not supported in fitsio). You can use them as a column in a binary table but that is separate in healsparse.

**Comment by esheldon** [comment]
You could use a small integer type.

**Comment by erykoff** [comment]
Okay, I just tried something but can make it better and do it automatically on serialization I think.

**Review by fjaviersanchez — APPROVED** [review]
Thanks @erykoff. It looks good to me.

**Comment by erykoff** [comment]
This was properly fixed on #129

**Pull request closed without merging**
