### PR TITLE
Add functionality to concatenate maps together in memory-efficient way

### PR DESCRIPTION
**Pull request by erykoff**
This PR also fixes several bugs when using astropy.io.fits instead of fitsio, and adds tests for these cases.

### CODE REVIEW

**Review by fjaviersanchez — APPROVED** [review]
Thanks a lot @erykoff. Everything looks good to me and tests pass in my laptop.

PS: I really enjoyed seeing the new `hs` extension 😄

**Comment by erykoff** [comment]
@fjaviersanchez Are you happy with the name `cat_healsparse_files` rather than something else (`merge`? `append`?).  And you can blame @esheldon for the `.hs` extension.

**Comment by esheldon** [comment]
Its amazing the things I don't remember, like picking a `.hs` extension

**Comment by fjaviersanchez** [comment]
Yes, I'm happy with `cat_healsparse_files` (it has a `cat` in the name!) 🐱

**Pull request merged**
