### PR TITLE
Added functionality to query valid pixels position

### PR DESCRIPTION
**Pull request by fjaviersanchez**
I just added functionality to address #44

### CODE REVIEW

**Review by erykoff — APPROVED** [review]
Looks good!

**Comment by fjaviersanchez** [comment]
Thanks! I'll update the tutorial to add this functionality too and merge afterwards.

**Comment by fjaviersanchez** [comment]
Okay, done! @erykoff would you mind taking a look at the cells that I added to the notebook before I merge this PR, please?

Attaching a screenshot of the changes here so it's easier to review :) 

Screen Shot 2020-03-24 at 1 22 44 PM

**Comment by erykoff** [comment]
This is fine, but a bit circular on the first two.  Note that `hsp_map_values = hsp_map.get_values_pix(hsp_map.valid_pixels)` is more direct, but I guess you also want access to the positions for the plotting below.  So I would make a comment about that.

**Pull request merged**
